src/Entity/Level.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LevelRepository")
 */
class Level
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $unlock_score;

    /**
     * @ORM\Column(type="integer")
     */
    private $score;

    /**
     * @ORM\Column(type="integer")
     */
    private $tried_num = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $passed_num = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $total_rating = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $rated_num = 0;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $tags;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $answer;

    /**
     * @ORM\Column(type="boolean")
     */
    private $under_review;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="levels")
     */
    private $author_user;

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUnlockScore(): ?int
    {
        return $this->unlock_score;
    }

    public function setUnlockScore(int $unlock_score): self
    {
        $this->unlock_score = $unlock_score;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getTriedNum(): ?int
    {
        return $this->tried_num;
    }

    public function setTriedNum(int $tried_num): self
    {
        $this->tried_num = $tried_num;

        return $this;
    }

    public function getTotalRating(): ?int
    {
        return $this->total_rating;
    }

    public function setTotalRating(int $total_rating): self
    {
        $this->total_rating = $total_rating;

        return $this;
    }

    public function getRatedNum(): ?int
    {
        return $this->rated_num;
    }

    public function setRatedNum(int $rated_num): self
    {
        $this->rated_num = $rated_num;

        return $this;
    }

    public function getPassedNum(): ?int
    {
        return $this->passed_num;
    }

    public function setPassedNum(int $passed_num): self
    {
        $this->passed_num = $passed_num;

        return $this;
    }

    public function getTags(): ?array
    {
        return $this->tags;
    }

    public function setTags(?array $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getAnswer(): ?string
    {
        return $this->answer;
    }

    public function setAnswer(string $answer): self
    {
        $this->answer = $answer;

        return $this;
    }

    public function getUnderReview(): ?bool
    {
        return $this->under_review;
    }

    public function setUnderReview(bool $under_review): self
    {
        $this->under_review = $under_review;

        return $this;
    }

    public function getAuthorUser(): ?User
    {
        return $this->author_user;
    }

    public function setAuthorUser(?User $author_user): self
    {
        $this->author_user = $author_user;

        return $this;
    }
}

templates/base.html.twig
<!doctype html>
<html lang="zh-Hans">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

  <title>{% block title %}謎.Games{% endblock %}</title>
  
  {% block javascripts %}
  <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdn.bootcss.com/semantic-ui/2.3.1/semantic.min.js"></script>
  {% endblock %}
  {% block stylesheets %}
  <link href="https://cdn.bootcss.com/semantic-ui/2.3.1/semantic.min.css" rel="stylesheet">
  {% endblock %}

</head>
<body>
    {% block header %}{% endblock %}
    {% block main %}{% endblock %}
    {% block footer %}{% endblock %}
    {% block post_body_javascripts %}{% endblock %}
      {% block track_code %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-100793414-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-100793414-2');
    </script>
    <div style="display:none">
    <script src="https://s19.cnzz.com/z_stat.php?id=1274462125&web_id=1274462125" language="JavaScript"></script>
    </div>
   {% endblock %}
</body>
</html>

templates/editor.html.twig
{% extends 'index.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <style>
    #editor { 
        height:300px;
        width:100%;
    }
    </style>
{% endblock %}
{% block main %}

  <div class="ui main container">
  
    <h2 class="ui dividing header">关卡编辑器</h2>

    {% if can_propose == false %}
  <div class="ui negative message">
    <div class="header">积分不足</div>
    <p>您需要至少30积分以解锁关卡提交</p></div>
    {% endif %}

    <form class="ui form" method="post">
      <div class="five fields">
        <div class="field">
          <label>关卡名</label>
          <input type="text" name="level-name" value="{{level.name|default}}">
        </div>
        <div class="field">
          <label>（建议）可获取积分</label>
          <input type="number" name="score" value="{{level.score|default}}">
        </div>
        <div class="field">
          <label>（建议）解锁积分</label>
          <input type="number" name="unlock-score" value="{{level.unlockScore|default}}">
        </div>
        <div class="field">
          <label>作者</label>
          <input type="text" name="author" value="{{level.author|default}}">
        </div>
        <div class="field">
          <label>答案</label>
          <input type="text" name="answer" value="{{level.answer|default}}">
        </div>
      </div>
      <div class="field">
        <label>标签</label>
        <input type="text" name="tags" placeholder="green|简单,red|逆向,..." value="{{level.tags|default|join(',')}}">
        <p style="padding: 8px 0">可用颜色：
        <a class="ui red tiny label">red</a>, <a class="ui orange tiny label">orange</a>,
        <a class="ui yellow tiny label">yellow</a>, <a class="ui olive tiny label">olive</a>,
        <a class="ui green tiny label">green</a>, <a class="ui teal tiny label">teal</a>,
        <a class="ui blue tiny label">blue</a>, <a class="ui violet tiny label">violet</a>,
        <a class="ui purple tiny label">purple</a>, <a class="ui pink tiny label">pink</a>,
        <a class="ui brown tiny label">brown</a>, <a class="ui grey tiny label">grey</a>,
        <a class="ui black tiny label">black</a></p>
      </div>
      
      <div class="field">
        <textarea name="code" style="display: none">{{code|default}}</textarea>
        <div id="editor">{{code|default}}</div>
      </div>

      <p>* 关卡使用 <a href="https://www.kancloud.cn/yunye/twig-cn/159458">Twig</a> 编写，推荐基于 (extends) <a href="/res/level_base.html.twig">level_base.html.twig</a> 模板修改。</p>
      <p>* 您可以使用模板自带的 <a href="https://semantic-ui.com/introduction/getting-started.html">Semantic UI 框架</a></p>
      <p>* 我们鼓励您包括关卡的解决思路以供审核（请使用注释表明思路，会在审核时候删去）。</p>
      <p>* 若需要包含 php 代码，请使用注释包括在关卡内，审核时会人工转换成 php。请勿提交恶意 javascript 脚本或 php 代码。</p>
      <p>* 您同意我们在不修改关卡原意的情况下对关卡进行修改（包括但不限于关卡内容，标签，分数等）。</p>
      <p>* 关卡审核通过后作者将获得 {关卡积分*5} 积分作为奖励。</p>
      <p>* 由于关卡都是人工审核的，如果您有任何建议或意见也欢迎一同提交。</p>
      <button class="ui teal button" type="submit" {{can_propose?"":"disabled"}}>{{can_edit?"提交":"提交审核"}}</button>
      <button class="ui button" type="submit" formaction="preview" formtarget="_blank" {{can_propose?"":"disabled"}}>预览</button>
    </form>
  </div>

{% endblock %}

{% block post_body_javascripts %}
<script src="https://cdn.bootcss.com/ace/1.3.3/ace.js"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.session.setMode("ace/mode/twig");
    editor.session.on("change", function () {
      $('textarea[name="code"]').val(editor.session.getValue());
    });
</script>
{% endblock %}

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    {{ parent() }}
    <link href="/assets/css/index.css" rel="stylesheet">
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="/assets/js/tablesort.js"></script>
{% endblock %}
{% block header %}
  <div class="ui small modal">
        <div class="content">
            <form class="ui form" style="padding:10px" method="post" action="/sync">
                <div class="two fields">
                  <div class="field">
                    <label>邮箱</label>
                    <input type="email" name="email" placeholder="someone@example.org">
                  </div>
                  <div class="field">
                    <label>显示名</label>
                    <input type="text" name="display_name" placeholder="(留空使用邮箱名/不修改)">
                  </div>
                </div>
                <div class="field">
                  <label>密码</label>
                  <input type="password" name="password" placeholder="设置一个密码/填写您上次用的密码">
                </div>
                <div class="field">
                  <div class="ui checkbox">
                    <input type="checkbox" name="accept_terms" tabindex="0">
                    <label>我已阅读并同意本网站的<a href="eula.html">用户协议</a>。</label>
                  </div>
                </div>
                <button class="ui teal button" type="submit"><i class="sync icon"></i>同步进度</button>
              </form>
        </div>
    </div>
  <div class="ui inverted teal vertical masthead center aligned segment">

    <div class="ui container">
      <div class="ui large secondary menu">
        <div class="right item">
          <a class="ui inverted button" href="/editor/new">提交关卡</a>
          <a class="ui inverted button" onclick="$('.ui.modal').modal('show');">同步进度</a>
        </div>
      </div>
    </div>

    <div class="ui text container">
      <h1 class="ui inverted header">
        謎.Games
      </h1>
      <h2>解决「謎」题吧</h2>
    </div>

  </div>
{% endblock %}

{% block main %}

  <div class="ui main container">
    <div class="ui two column stackable grid container">
      <div class="twelve wide left floated column">
        <div class="ui three column middle aligned grid">
          <div class="eleven wide left floated column">
            <div class="ui green progress" id="levels_progress" data-value="{{ user.getPassedLevels|length }}" data-total="{{ levels|length }}">
              <div class="bar">
                <div class="progress"></div>
              </div>
              <div class="label">关卡进度</div>
            </div>
          </div>
          <div class="two wide right floated column">
            <div class="ui small statistic">
              <div class="value">{{ user.score }}</div>
              <div class="label">积分</div>
            </div>
          </div>
          <div class="two wide right floated column">
            <div class="ui small statistic">
              <div class="value">{{ rank }}</div>
              <div class="label">排名</div>
            </div>
          </div>
        </div>
        <h2 class="ui horizontal header divider">关卡列表</h2>
        <table class="ui very basic sortable padded table">
          <thead>
            <tr>
              <th class="collapsing"></th>
              <th class="collapsing">关卡</th>
              <th>标题</th>
              <th class="right aligned collapsing">作者</th>
              <th class="right aligned collapsing">积分</th>
              <th class="right aligned collapsing">通过率</th>
              <th class="right aligned collapsing">评价</th>
            </tr>
          </thead>
          <tbody>
          {% for level in levels %}
            <tr>
              <td data-sort-value="{{level.getUnlockScore}}">
                {% if level.id in user.getPassedLevels %}<i class="large green check icon"></i>{% endif %}
                {% if level.id not in user.getPassedLevels and user.score < level.unlockScore %}
                  <div class="ui icon" data-tooltip="{{level.getUnlockScore}} 点积分解锁" data-inverted="inverted"><i class="large lock icon"></i></div>
                {% endif %}
              </td>
              <td>{{level.id}}</td>
              <td>
                <a href="nazo/{{level.id}}"}>{{level.name}}</a>

                {% if level.underReview %}
                  <a href="editor/edit/{{level.id}}"}>(审核)</a>
                {% endif %}
                {% for tag in level.tags %}
                  {% if tag!="" %}
                  {% set tagcolor = tag|split('|') %}
                  <span class="right_floated tags">
                    <a class="ui {{tagcolor[0]}} tiny label">{{tagcolor[1]}}</a>
                  </span>
                  {% endif %}
                {% endfor %}
              </td>
              <td class="right aligned">{{level.author}}</td>
              <td class="right aligned">{{level.score}}</td>
              <td class="right aligned">{{level.getPassedNum}}/{{level.getTriedNum}}({{(level.getPassedNum/(level.getTriedNum==0?1:level.getTriedNum))*100//1}}%)</td>
              <td class="right aligned">{{level.getRatedNum==0? "--": ((level.getTotalRating/level.getRatedNum)|number_format(1)) }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="three wide right floated column">
        <h2 class="ui dividing header">排行榜</h2>
        <table class="ui very basic table">
          <tbody>
            {% for user in top10 %}
            <tr>
              <td class="collapsing">{{ loop.index }}</td>
              <td>{{user.getDisplayName}}</td>
              <td>{{user.getScore}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock %}

{% block footer %}
  <div class="ui teal inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">链接</h4>
          <div class="ui inverted link list">
            <a href="eula.html" class="item">用户协议</a>
          </div>
        </div>

        <div class="seven wide column">
          <h4 class="ui inverted header">关于</h4>
          <p>这是一个<a href="https://harrynull.tech">咸鱼</a>做的解谜网站</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block post_body_javascripts %}
  <script>
    $('#levels_progress').progress({
      label: 'ratio',
      text: {
        ratio: '{value} / {total}'
      },
      showActivity: false
    });
    $('.ui.form').form({
    fields: {
      email           : 'empty',
      password        : ['minLength[6]', 'empty'],
      accept_terms    : 'checked'
    }
  });
  $('.table').tablesort();
  </script>
  
{% endblock %}